import { useEffect, useMemo, useState } from 'react';
import { profile } from './data/profile';
import './App.css';

const statuses = ['CAPTURED', 'PENDING', 'FAILED'];
const statusTone = { CAPTURED: 'success', PENDING: 'pending', FAILED: 'failed' };

function randomTransaction() {
  const status = statuses[Math.floor(Math.random() * statuses.length)];
  const amount = (Math.random() * 4900 + 100).toFixed(2);
  return { id: `txn_${Math.random().toString(36).slice(2, 9)}`, amount, currency: Math.random() > 0.35 ? 'INR' : 'USD', status };
}

function Navbar() { return <nav className="site-nav"><div className="shell nav-inner"><a className="display brand" href="#top">Adarsh Singh<span>/</span></a><div className="nav-links">{['Flow', 'Projects', 'Stack', 'Experience', 'Contact'].map((item) => <a key={item} href={`#${item.toLowerCase()}`}>{item}</a>)}</div><a className="mono nav-status" href={`mailto:${profile.email}`}><span /> Available for work</a></div></nav>; }

function TransactionFeed() {
  const [transactions, setTransactions] = useState(() => Array.from({ length: 6 }, randomTransaction));
  useEffect(() => { if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return undefined; const interval = window.setInterval(() => setTransactions((current) => [...current.slice(-5), randomTransaction()]), 2200); return () => window.clearInterval(interval); }, []);
  return <div className="feed panel"><div className="feed-head"><div><span className="section-kicker">Live sandbox</span><h2 className="display">Transaction feed</h2></div><span className="feed-live mono"><i /> LIVE</span></div><p className="feed-note">Simulated feed for illustration. No real merchant data.</p><div className="feed-list">{transactions.map((transaction) => <div className="transaction" key={transaction.id}><span className="mono txn-id">{transaction.id}</span><span className="mono txn-amount">{transaction.currency === 'INR' ? '₹' : '$'}{transaction.amount}</span><span className={`pill pill-${statusTone[transaction.status]}`}>{transaction.status}</span></div>)}</div></div>;
}

function Hero() { return <header className="hero" id="top"><div className="shell hero-grid"><div className="hero-copy"><div className="eyebrow mono">FULL-STACK / PAYMENTS / RELIABILITY</div><h1 className="display">I build the APIs that <em>move money</em> reliably.</h1><p className="hero-sub">{profile.title} who connects resilient backend systems to clear, useful product interfaces for the people operating them.</p><div className="hero-actions"><a className="button" href="#projects">View selected work <span>↗</span></a><a className="button button-secondary" href="/resume.pdf" target="_blank" rel="noreferrer">Resume <span>↓</span></a></div><div className="hero-meta mono"><span>{profile.locations}</span><span>{profile.workMode}</span></div></div><TransactionFeed /></div></header>; }

function KpiStrip() { return <section className="kpi-strip"><div className="shell kpi-grid">{[['50+', 'gateways integrated'], ['4+', 'years since June 2022'], ['INR + Intl', 'payment rails'], ['Node · Java · React · PHP', 'core technologies']].map(([value, label]) => <div className="kpi" key={label}><strong className="mono">{value}</strong><span>{label}</span></div>)}</div></section>; }

function PaymentFlow() { const nodes = ['Merchant', 'API layer', 'Gateway router', 'Payment gateway', 'Webhook handler', 'Reconciliation']; return <section className="section" id="flow"><div className="shell"><div className="section-heading"><div><span className="section-kicker">01 / Architecture</span><h2 className="section-title">Payment flow, end to end.</h2></div><p className="section-aside">Designed for clear ownership, observable states, and resilient callbacks.</p></div><div className="flow-scroll panel"><svg className="flow-svg" viewBox="0 0 1100 180" role="img" aria-label="Payment flow from merchant to reconciliation"><path className="flow-line" d="M85 80 H1015" /><path className="async-line" d="M1015 130 H85" /><text x="550" y="164" textAnchor="middle" className="flow-label">async callback</text>{nodes.map((node, index) => <g key={node} className="flow-node" transform={`translate(${45 + index * 202}, 48)`}><rect width="120" height="64" rx="3" /><circle cx="16" cy="18" r="4" /><text x="16" y="43">{node}</text><text x="16" y="56" className="node-number">0{index + 1}</text></g>)}</svg></div></div></section>; }

function Projects() { const [filter, setFilter] = useState('All'); const filters = ['All', 'FinTech', 'Automation', 'Backend']; const projects = useMemo(() => filter === 'All' ? profile.projects : profile.projects.filter((project) => project.category === filter), [filter]); return <section className="section section-muted" id="projects"><div className="shell"><div className="section-heading"><div><span className="section-kicker">02 / Selected work</span><h2 className="section-title">Systems with a job to do.</h2></div><div className="filter-row">{filters.map((item) => <button className={`filter ${filter === item ? 'filter-active' : ''}`} key={item} onClick={() => setFilter(item)}>{item}</button>)}</div></div><div className="project-grid">{projects.map((project) => <article className="project-card panel" key={project.title}><div className="project-top"><span className="mono project-service">{project.service}</span><span className={`pill pill-${project.statusTone}`}>{project.status}</span></div><h3 className="display">{project.title}</h3><p>{project.description}</p><div className="impact"><span className="mono">IMPACT</span>{project.impact}</div><div className="tags">{project.tech.map((tag) => <span className="mono" key={tag}>{tag}</span>)}</div></article>)}</div></div></section>; }

function Stack() { return <section className="section" id="stack"><div className="shell"><div className="section-heading"><div><span className="section-kicker">03 / Stack</span><h2 className="section-title">Tools I reach for often.</h2></div></div><div className="stack-grid">{profile.stack.map((group) => <div className="stack-group" key={group.name}><h3 className="mono">{group.name}</h3>{group.skills.map(([skill, level]) => <div className="skill-row" key={skill}><span>{skill}</span><span className="mono skill-level">{level}</span></div>)}</div>)}</div></div></section>; }

function Experience() { return <section className="section section-muted" id="experience"><div className="shell"><div className="section-heading"><div><span className="section-kicker">04 / Experience</span><h2 className="section-title">Reliable by repetition.</h2></div></div><div className="experience-grid"><div><div className="timeline-dot" /><span className="mono exp-date">{profile.experience}</span></div><div><h3 className="display">Senior Software Engineer</h3><p className="exp-company">{profile.company}</p><ul><li>Integrated payment gateways across INR and international rails.</li><li>Built REST APIs, webhooks, and reconciliation-ready status flows.</li><li>Optimized MySQL queries and Redis caching for frequent transaction checks.</li></ul></div><div className="education"><span className="mono">EDUCATION</span><p>{profile.education}</p></div></div></div></section>; }

function Contact() { const [copied, setCopied] = useState(false); const copyEmail = async () => { await navigator.clipboard?.writeText(profile.email); setCopied(true); window.setTimeout(() => setCopied(false), 1600); }; return <section className="section contact-section" id="contact"><div className="shell"><div className="contact-block"><div><span className="mono endpoint"><i /> POST /contact <b>200</b></span><h2 className="display">Let’s build something dependable.</h2><p>Open to backend, payments, and platform engineering conversations.</p></div><div className="contact-links"><div className="email-line"><span className="mono">{profile.email}</span><button className="button" onClick={copyEmail}>{copied ? 'Copied' : 'Copy'} <span>⧉</span></button></div><a href={profile.linkedin} target="_blank" rel="noreferrer" className="linkedin">LinkedIn <span>↗</span></a><a href={profile.github} target="_blank" rel="noreferrer" className="linkedin">GitHub <span>↗</span></a></div></div></div></section>; }

function Footer() { return <footer><div className="shell footer-inner"><span className="mono">© {new Date().getFullYear()} / {profile.name}</span><span>Built around reliable systems.</span><a href="#top" className="mono">BACK TO TOP ↑</a></div></footer>; }

export default function App() { return <div><Navbar /><Hero /><KpiStrip /><PaymentFlow /><Projects /><Stack /><Experience /><Contact /><Footer /></div>; }
